import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-fundraising',
  title: 'AI Company Fundraising',
  description: 'Funding rounds raised by AI companies, with their investors and sources.',
  license: 'CC-BY-4.0',
  noun: { one: 'round', other: 'rounds' },
  // One round per company and stage. The website is cut to its home page, so variants of
  // one site compare equal.
  identity: ['website', 'stage'],
  fields: {
    company: {
      type: 'text',
      label: 'Company',
      required: true,
      max: 120,
      help: 'The name the company uses; when the source also gives a name in another script, add it in brackets, e.g. Zhipu AI (智谱).',
    },
    website: { type: 'url', label: 'Website', required: true, homePage: true, help: "The company's own website." },
    focus: {
      type: 'text',
      label: 'What it builds',
      required: true,
      max: 140,
      help: 'A short phrase, e.g. AI agents for insurance underwriting.',
    },
    sector: {
      type: 'enum',
      label: 'Sector',
      required: true,
      help: 'The one sector its main product fits best. Chips, compute, networking and data-center power are infrastructure; agents sold to businesses are enterprise unless a sector below fits better.',
      values: [
        'foundation-models',
        'infrastructure',
        'developer-tools',
        'security',
        'robotics',
        'health',
        'finance',
        'enterprise',
        'consumer',
        'defense',
        'other',
      ],
      valueLabels: {
        'foundation-models': 'Foundation models',
        infrastructure: 'Chips, cloud & data centers',
        'developer-tools': 'Developer & data tools',
        security: 'Security & governance',
        robotics: 'Robotics & physical AI',
        health: 'Health & life sciences',
        finance: 'Finance & insurance',
        enterprise: 'Business apps & agents',
        consumer: 'Consumer',
        defense: 'Defense & public sector',
        other: 'Other',
      },
    },
    stage: {
      type: 'enum',
      label: 'Round',
      required: true,
      help: 'Pre-A, Pre-A+ and Pre-A++ are pre-series-a. An extension or plus round takes the stage it extends (Series B+ is series-b). Series E and later are series-e-plus. Growth, convertible and unnamed rounds are other.',
      values: [
        'angel',
        'pre-seed',
        'seed',
        'pre-series-a',
        'series-a',
        'series-b',
        'series-c',
        'series-d',
        'series-e-plus',
        'strategic',
        'other',
      ],
      valueLabels: {
        angel: 'Angel',
        'pre-seed': 'Pre-seed',
        seed: 'Seed',
        'pre-series-a': 'Pre-Series A',
        'series-a': 'Series A',
        'series-b': 'Series B',
        'series-c': 'Series C',
        'series-d': 'Series D',
        'series-e-plus': 'Series E and later',
        strategic: 'Strategic',
        other: 'Other',
      },
    },
    round: {
      type: 'text',
      label: 'Round name',
      max: 60,
      help: "The round's own name when it says more than the stage, e.g. Pre-A++ or Series B extension.",
    },
    announced_on: {
      type: 'date',
      label: 'Announced',
      required: true,
      help: 'The day the company, an investor or the first news report made the round public.',
    },
    amount_usd: {
      type: 'number',
      label: 'Amount (USD)',
      min: 0,
      display: 'usd',
      help: 'The amount raised, only when the source states it in US dollars or gives its own conversion. Never convert it yourself.',
    },
    amount_stated: {
      type: 'text',
      label: 'Amount as stated',
      max: 80,
      help: 'When the source gives the amount in another currency or as a range, in its words, e.g. €20 million or tens of millions of yuan.',
    },
    valuation_usd: {
      type: 'number',
      label: 'Valuation (USD)',
      min: 0,
      display: 'usd',
      help: 'Only when the source states it in US dollars.',
    },
    investors: {
      type: 'text',
      label: 'Investors',
      max: 240,
      help: 'As the source names them, lead investors first, separated by commas.',
    },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      required: true,
      max: 3,
      help: 'The city the company is headquartered in, in English, e.g. ["San Francisco"]; two when it names two headquarters, e.g. ["New York", "Tel Aviv"].',
    },
    country: {
      type: 'text',
      label: 'Country',
      required: true,
      max: 60,
      help: 'The country the company is based in, e.g. United States; two separated by a slash when the source names both.',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      help: "Where the company's headquarters is; for two countries, the first.",
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
  },
  accept: { announced_on: { from: 'today-90', to: 'today' } },
  example: {
    data: {
      company: 'Example Robotics',
      website: 'https://example.com/',
      focus: 'Warehouse robots that learn new tasks from video',
      sector: 'robotics',
      stage: 'series-a',
      announced_on: '2026-09-15',
      amount_usd: 25000000,
      investors: 'Example Ventures, Sample Capital',
      city: ['San Francisco'],
      country: 'United States',
      region: 'americas',
    },
    source_url: 'https://example.com/news/series-a',
    evidence:
      'Example Robotics today announced it has raised $25 million in Series A funding led by Example Ventures, with participation from Sample Capital.',
  },
  table: {
    columns: ['company', 'focus', 'stage', 'amount_usd', 'announced_on', 'investors', 'city', 'country'],
    defaultSort: '-announced_on',
    previewTitle: 'Latest rounds',
    previewColumns: ['company', 'focus', 'stage', 'amount_usd', 'announced_on', 'city'],
    fallback: { amount_usd: 'amount_stated' },
  },
  charts: [
    { kind: 'count', title: 'Rounds in the last 30 days', where: { announced_on: { from: 'today-30' } } },
    { kind: 'over-time', title: 'Rounds by week announced', field: 'announced_on', bucket: 'week' },
    { kind: 'by-category', title: 'By round', field: 'stage' },
    { kind: 'by-category', title: 'By sector', field: 'sector' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'by-category', title: 'Top cities', field: 'city' },
    {
      kind: 'histogram',
      title: 'Round size (USD)',
      field: 'amount_usd',
      edges: [0, 1000000, 5000000, 10000000, 25000000, 50000000, 100000000, 250000000, 1000000000],
    },
  ],
  scope: {
    in: 'Funding rounds raised by companies whose main product is AI, or the chips, cloud, data centers or power built for it: angel to late-stage rounds, including SAFEs, convertible notes and strategic investments, announced in the last 90 days.',
    out: 'Acquisitions and mergers; IPOs and share placements by listed companies; loans, credit lines and grants; funds raised by investment firms; rounds reported as in talks or not yet closed; companies that only use AI as a feature.',
  },
  sourceHints: [
    "The company's own announcement or blog",
    "Lead investors' announcements",
    'Wire services such as Business Wire and PR Newswire',
    'Business and tech press such as Reuters, TechCrunch and 36Kr',
    'Not GlobeNewswire when the release is also elsewhere: it often refuses automated requests, so maintainers cannot check it',
  ],
  recheckAfterDays: 90,
  notify: { line: '{company} · {stage} · {amount_usd} · {city} · {sector}' },
});
