import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'endurance-races',
  title: 'Half Marathons, Trails & Triathlons',
  description: 'Half marathons, trail and ultra races, and triathlons around the world that hold a label or belong to a major series: dates, places and registration.',
  license: 'CC-BY-4.0',
  noun: { one: 'race', other: 'races' },
  // One record per edition. Series sites give each race its own page, so the page is kept
  // whole rather than cut to the home page.
  identity: ['url', 'race_date'],
  fields: {
    name: {
      type: 'text',
      label: 'Race',
      required: true,
      max: 140,
      help: 'The race’s official name in English as its page writes it, e.g. IRONMAN 70.3 Xiamen or Lantau 50 by UTMB; add a name in another script in brackets, e.g. Shanghai Half Marathon (上海半程马拉松).',
    },
    url: {
      type: 'url',
      label: 'Website',
      required: true,
      help: 'The race’s own website, or its page on the series site, e.g. https://www.ironman.com/races/im703-xiamen.',
    },
    race_date: { type: 'date', label: 'Race day', required: true, help: 'The day the main race starts.' },
    sport: {
      type: 'enum',
      label: 'Sport',
      required: true,
      help: 'half-marathon (a 21.1 km road race), trail (a trail or ultra race), triathlon.',
      values: ['half-marathon', 'trail', 'triathlon'],
      valueLabels: { 'half-marathon': 'Half marathon', trail: 'Trail or ultra', triathlon: 'Triathlon' },
    },
    series: {
      type: 'enum',
      label: 'Label or series',
      required: true,
      help: 'The highest it holds, as a page states it: world-athletics (a World Athletics label), aims (an AIMS member race), national (a national federation’s top label), utmb (a UTMB World Series event, Major or Final), golden-trail (the Golden Trail World Series), ironman (a full-distance IRONMAN), ironman-70-3 (an IRONMAN 70.3), challenge (Challenge Family), t100 (the T100 Triathlon World Tour).',
      values: ['world-athletics', 'aims', 'national', 'utmb', 'golden-trail', 'ironman', 'ironman-70-3', 'challenge', 't100'],
      valueLabels: {
        'world-athletics': 'World Athletics label',
        aims: 'AIMS member',
        national: 'National label',
        utmb: 'UTMB World Series',
        'golden-trail': 'Golden Trail Series',
        ironman: 'IRONMAN',
        'ironman-70-3': 'IRONMAN 70.3',
        challenge: 'Challenge Family',
        t100: 'T100',
      },
    },
    distance_km: {
      type: 'number',
      label: 'Distance',
      min: 0,
      max: 1000,
      unit: 'km',
      help: 'The main race’s distance in km: 21.1 for a half marathon, the longest trail distance, 113 for an IRONMAN 70.3 and 226 for a full distance.',
    },
    climb_m: {
      type: 'number',
      label: 'Climb',
      min: 0,
      unit: 'm',
      help: 'For a trail race: the main distance’s total climb in metres, when the page states it.',
    },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      required: true,
      max: 2,
      help: 'The town or city it starts in, in English, e.g. ["Chamonix"]; two when it runs from one to another.',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Country or area',
      required: true,
      max: 1,
      help: 'The country or area in English, e.g. ["France"], ["Hong Kong"] or ["Chinese Taipei"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    registration_closes: {
      type: 'date',
      label: 'Registration closes',
      help: 'The last day to register or to enter the lottery, when the page states one.',
    },
    entry_fee: {
      type: 'text',
      label: 'Entry fee',
      max: 60,
      help: 'The main race’s entry fee as the page writes it, e.g. €95 or US$425; the standard fee when there are several.',
    },
    field_size: {
      type: 'number',
      label: 'Field size',
      min: 0,
      help: 'The number of places in the main race, or last edition’s finishers, when the page states it.',
    },
  },
  rules: [{ field: 'race_date', notBefore: 'registration_closes' }],
  accept: { race_date: { from: 'today', to: 'today+400' } },
  example: {
    data: {
      name: 'Example Valley Trail by UTMB',
      url: 'https://examplevalley.utmb.world/',
      race_date: '2027-05-14',
      sport: 'trail',
      series: 'utmb',
      distance_km: 105,
      climb_m: 5900,
      city: ['Springfield'],
      country: ['United States'],
      region: 'americas',
      registration_closes: '2027-03-31',
      entry_fee: 'US$320',
    },
    source_url: 'https://examplevalley.utmb.world/',
    evidence:
      'Example Valley Trail by UTMB, part of the UTMB World Series, starts in Springfield on May 14, 2027. The 100K covers 105 km with 5,900 m of climbing; registration closes on March 31, 2027.',
  },
  table: {
    columns: ['name', 'sport', 'race_date', 'city', 'country', 'series', 'distance_km', 'registration_closes'],
    defaultSort: 'race_date',
    defaultFilter: { race_date: { from: 'today' } },
    previewTitle: 'Next races',
    previewColumns: ['name', 'sport', 'race_date', 'city', 'country'],
  },
  charts: [
    { kind: 'count', title: 'Upcoming races', where: { race_date: { from: 'today' } } },
    { kind: 'over-time', title: 'Races by month', field: 'race_date', bucket: 'month' },
    { kind: 'by-category', title: 'By sport', field: 'sport' },
    { kind: 'by-category', title: 'By label or series', field: 'series' },
    { kind: 'by-category', title: 'Top countries', field: 'country' },
    { kind: 'by-category', title: 'By region', field: 'region' },
  ],
  scope: {
    in: 'Half marathons that hold a World Athletics label, are AIMS members or hold a national federation’s top label; trail and ultra races in the UTMB World Series (including its Majors and Finals) or the Golden Trail World Series; and IRONMAN, IRONMAN 70.3, Challenge Family and T100 triathlons — anywhere in the world, held on or after today.',
    out: 'Full marathons (they belong in World Marathons); races with none of those labels or series; virtual races; obstacle races; fun runs; past editions.',
  },
  sourceHints: [
    'The race’s own website or its page on the series site',
    'The World Athletics label road race list and the AIMS calendar, as leads: cite the race’s own page',
    'The UTMB World Series and Golden Trail World Series calendars',
    'The IRONMAN, Challenge Family and T100 race calendars',
  ],
  recheckAfterDays: 30,
  notify: { line: '{name} · {sport} · {race_date} · {city} · {country}' },
});
