import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'robot-launches',
  title: 'Robot Launches',
  description: 'Humanoid robots, robot dogs and home robots: when each was shown working, opened for preorders, went on sale and started shipping, at what price and where.',
  license: 'CC-BY-4.0',
  noun: { one: 'milestone', other: 'milestones' },
  // One record per robot and milestone: a robot that is unveiled, then opens preorders, then
  // ships has three records, each announced when it is verified.
  identity: ['product', 'milestone'],
  fields: {
    product: {
      type: 'text',
      label: 'Robot',
      required: true,
      max: 120,
      help: 'The robot’s name with its maker’s brand, in English as the maker writes it, e.g. Unitree R1, Figure 03 or 1X NEO; add a Chinese name in brackets when the maker uses one, e.g. AgiBot A2 (远征 A2).',
    },
    maker: {
      type: 'tags',
      names: true,
      label: 'Maker',
      required: true,
      max: 1,
      help: 'The company’s short English name, e.g. ["Unitree"], ["Figure"], ["1X"] or ["UBTech"].',
    },
    kind: {
      type: 'enum',
      label: 'Kind',
      required: true,
      help: 'humanoid (a robot with a human-like body: legs, or a torso with two arms on a base), quadruped (a four-legged robot such as a robot dog), home-robot (a general-purpose robot for the home that does chores or keeps people company, other than a humanoid).',
      values: ['humanoid', 'quadruped', 'home-robot'],
      valueLabels: { humanoid: 'Humanoid', quadruped: 'Robot dog or quadruped', 'home-robot': 'Home robot' },
    },
    milestone: {
      type: 'enum',
      label: 'Milestone',
      required: true,
      help: 'unveiled (first shown working, in public or on video), preorder (orders or deposits open to the public), on-sale (anyone in a market can buy it outright), shipping (the first units are delivered to buyers).',
      values: ['unveiled', 'preorder', 'on-sale', 'shipping'],
      valueLabels: {
        unveiled: 'Unveiled',
        preorder: 'Preorders open',
        'on-sale': 'On sale',
        shipping: 'Shipping to buyers',
      },
    },
    date: { type: 'date', label: 'Date', required: true, help: 'The day it happened, as a page states it.' },
    price_usd: {
      type: 'number',
      label: 'Price (USD)',
      min: 0,
      display: 'usd',
      help: 'The price a buyer pays for the robot as the maker states it, in US dollars at the day’s rate; for a starting price, that price. Leave it out for a deposit alone, and put the original in Price as stated.',
    },
    price_stated: {
      type: 'text',
      label: 'Price as stated',
      max: 80,
      help: 'The price as the page writes it, e.g. ¥39,900, from US$5,900 or US$20,000 or US$499 a month.',
    },
    markets: {
      type: 'tags',
      names: true,
      label: 'Where to buy',
      max: 10,
      help: 'Where buyers can order it, as the page names them, e.g. ["United States"] or ["China"]; ["Worldwide"] when the page says so.',
    },
    ships_on: {
      type: 'date',
      label: 'Planned shipping',
      help: 'For an unveiling or preorder: when the maker says deliveries start; the first of the month when it gives only the month.',
    },
    height_cm: {
      type: 'number',
      label: 'Height',
      min: 0,
      max: 400,
      unit: 'cm',
      help: 'For a humanoid: its standing height in centimetres, when the page states it.',
    },
    maker_country: {
      type: 'tags',
      names: true,
      label: 'Maker’s country',
      required: true,
      max: 1,
      help: 'Where the maker is based, in English, e.g. ["China"], ["United States"] or ["Norway"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      help: 'The maker’s region.',
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    url: {
      type: 'url',
      label: 'Official page',
      required: true,
      help: 'The maker’s page for the robot or for the announcement.',
    },
  },
  accept: { date: { from: 'today-365', to: 'today' } },
  example: {
    data: {
      product: 'Example H1',
      maker: ['Example Robotics'],
      kind: 'humanoid',
      milestone: 'preorder',
      date: '2026-09-22',
      price_usd: 19900,
      price_stated: 'US$19,900',
      markets: ['United States'],
      ships_on: '2027-03-01',
      height_cm: 165,
      maker_country: ['United States'],
      region: 'americas',
      url: 'https://example.org/h1',
    },
    source_url: 'https://example.org/news/h1-preorders',
    evidence:
      'Starting today, September 22, 2026, customers in the United States can preorder Example H1, our 165 cm home humanoid, for US$19,900, with deliveries beginning in March 2027.',
  },
  table: {
    columns: ['product', 'kind', 'milestone', 'date', 'price_usd', 'maker_country', 'markets'],
    defaultSort: '-date',
    previewTitle: 'Latest milestones',
    previewColumns: ['product', 'kind', 'milestone', 'date', 'price_usd'],
    fallback: { price_usd: 'price_stated' },
  },
  charts: [
    { kind: 'count', title: 'Milestones in the last 30 days', where: { date: { from: 'today-30' } } },
    { kind: 'over-time', title: 'Milestones by month', field: 'date', bucket: 'month' },
    { kind: 'by-category', title: 'By kind', field: 'kind' },
    { kind: 'by-category', title: 'By milestone', field: 'milestone' },
    { kind: 'by-category', title: 'Makers’ countries', field: 'maker_country' },
    { kind: 'by-category', title: 'Top makers', field: 'maker' },
    { kind: 'histogram', title: 'Price (USD)', field: 'price_usd', edges: [0, 2000, 10000, 20000, 50000, 100000] },
  ],
  scope: {
    in: 'Humanoid robots, four-legged robots such as robot dogs, and general-purpose home robots that do chores or keep people company, from makers anywhere in the world: the day each was first shown working, opened for preorders, went on sale and started shipping to buyers, in the last 12 months.',
    out: 'University and lab research robots not offered to customers; robot vacuums, mops, window cleaners, lawn mowers and pool robots; industrial arms, warehouse and delivery robots; drones and vehicles; toys and kits for children; renderings and plans with no working robot shown; promised dates that have not happened yet (they go in Planned shipping).',
  },
  sourceHints: [
    'The maker’s own announcement, product page and newsroom',
    'Press releases on wire services, such as PR Newswire and Business Wire',
    'IEEE Spectrum’s robotics coverage and major news, as leads, or as the source when the maker’s page cannot be read',
    'For Chinese makers: their official sites, Xinhua and IT之家 (ithome.com)',
  ],
  recheckAfterDays: 60,
  notify: { line: '{product} · {milestone} · {date} · {price_usd} · {maker_country}' },
});
