import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-accelerators',
  title: 'AI Accelerators & Grants',
  description: 'Accelerators, grants, fellowships, residencies and compute credits for AI founders and researchers, open now.',
  license: 'CC-BY-4.0',
  noun: { one: 'program', other: 'programs' },
  // One record per program page. When a program opens its next intake on the same page, the
  // record is corrected rather than added again.
  identity: ['url'],
  fields: {
    name: {
      type: 'text',
      label: 'Program',
      required: true,
      max: 160,
      help: "The program's name as it writes it, without the intake, e.g. Google for Startups Accelerator: AI First.",
    },
    organizer: { type: 'text', label: 'Run by', required: true, max: 120, help: 'The organization that runs or funds it.' },
    kind: {
      type: 'enum',
      label: 'Kind',
      required: true,
      help: 'accelerator: a cohort program that invests in or mentors teams (incubators too). grant: money that takes no equity, for a project or company. fellowship: funding or support for individuals. residency: a place to live or work on site. credits: cloud, compute or model API credits.',
      values: ['accelerator', 'grant', 'fellowship', 'residency', 'credits'],
      valueLabels: {
        accelerator: 'Accelerator',
        grant: 'Grant',
        fellowship: 'Fellowship',
        residency: 'Residency',
        credits: 'Credits',
      },
    },
    url: {
      type: 'url',
      label: 'Official page',
      required: true,
      help: 'The page people apply on, or the official page that links to the application.',
    },
    cohort: {
      type: 'text',
      label: 'Intake',
      max: 60,
      help: 'The intake the deadline belongs to, as the page names it, e.g. Winter 2027 batch or Call 3.',
    },
    deadline: {
      type: 'date',
      label: 'Deadline',
      openEnded: 'Rolling',
      help: 'The last day to apply for the next intake. Leave it out when the page says applications are open on a rolling basis.',
    },
    audience: {
      type: 'enum',
      label: 'For',
      required: true,
      help: 'Who applies: startups (companies and founding teams, including idea stage), researchers (academic or independent), students, or individuals (anyone applying as a person).',
      values: ['startups', 'researchers', 'students', 'individuals'],
      valueLabels: { startups: 'Startups', researchers: 'Researchers', students: 'Students', individuals: 'Individuals' },
    },
    funding_usd: {
      type: 'number',
      label: 'Funding (USD)',
      min: 0,
      display: 'usd',
      help: 'Cash per team or person, only when the page states it in US dollars; the most when it gives a range or says "up to". Never convert it yourself.',
    },
    funding_stated: {
      type: 'text',
      label: 'Funding as stated',
      max: 80,
      help: 'When the page gives the cash in another currency or in words, as written, e.g. up to £500,000.',
    },
    equity_pct: {
      type: 'number',
      label: 'Equity (%)',
      min: 0,
      max: 100,
      unit: '%',
      help: 'The share of the company the program takes, as stated; 0 when the page says it takes no equity.',
    },
    credits_usd: {
      type: 'number',
      label: 'Credits (USD)',
      min: 0,
      display: 'usd',
      help: 'Cloud, compute or API credits per team, when stated in US dollars; the most when it says "up to".',
    },
    format: {
      type: 'enum',
      label: 'Format',
      help: 'For programs with sessions or a place: in person, remote or hybrid. Leave it out for grants and credits.',
      values: ['in-person', 'remote', 'hybrid'],
      valueLabels: { 'in-person': 'In person', remote: 'Remote', hybrid: 'Hybrid' },
    },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      max: 8,
      help: 'For in-person and hybrid programs, each city it runs in, in English, e.g. ["San Francisco"]. Leave it out otherwise.',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      help: 'Where an in-person or hybrid program runs; otherwise where applicants must be based; global when it is remote and open to applicants anywhere.',
      values: ['global', 'americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        global: 'Global',
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
  },
  accept: { deadline: { from: 'today' } },
  example: {
    data: {
      name: 'Example AI Accelerator',
      organizer: 'Example Ventures',
      kind: 'accelerator',
      url: 'https://example.org/accelerator',
      cohort: 'Spring 2027',
      deadline: '2026-11-15',
      audience: 'startups',
      funding_usd: 150000,
      equity_pct: 7,
      format: 'in-person',
      city: ['Berlin'],
      region: 'europe',
    },
    source_url: 'https://example.org/accelerator',
    evidence:
      'Applications for the Spring 2027 cohort close on November 15, 2026. Each startup receives $150,000 for 7% equity and spends twelve weeks with us in Berlin.',
  },
  table: {
    columns: ['name', 'kind', 'deadline', 'funding_usd', 'equity_pct', 'credits_usd', 'audience', 'city', 'region'],
    defaultSort: 'deadline',
    defaultFilter: { deadline: { from: 'today' } },
    previewTitle: 'Closing soon',
    previewColumns: ['name', 'kind', 'deadline', 'funding_usd', 'region'],
    fallback: { funding_usd: 'funding_stated' },
  },
  charts: [
    { kind: 'count', title: 'Open for applications', where: { deadline: { from: 'today' } } },
    { kind: 'over-time', title: 'Deadlines by week', field: 'deadline', bucket: 'week' },
    { kind: 'by-category', title: 'By kind', field: 'kind' },
    { kind: 'by-category', title: 'Who can apply', field: 'audience' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'by-category', title: 'Top cities', field: 'city' },
    {
      kind: 'histogram',
      title: 'Funding per team (USD)',
      field: 'funding_usd',
      edges: [0, 10000, 50000, 100000, 250000, 500000, 1000000],
    },
  ],
  scope: {
    in: 'Accelerators, incubators, grants, fellowships, residencies and cloud, compute or model API credit programs that AI founders, teams or researchers can apply to, taking applications on a rolling basis or with a deadline on or after today. A general program counts when its page names AI as a focus.',
    out: 'Hackathons, competitions, prizes and bounties (they belong in AI Hackathons); programs only for one company’s staff or one school’s students; pitch events and demo days; paid courses and bootcamps; discounts and perks without credits or cash; programs that have closed for good.',
  },
  sourceHints: [
    'Official program and application pages',
    'Government and foundation funding calls',
    'Startup program pages of cloud, chip and AI model companies',
  ],
  recheckAfterDays: 14,
  notify: { line: '{name} · {kind} · {funding_usd} · deadline {deadline} · {region}' },
});
