import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-scams',
  title: 'AI Scam Alerts',
  description: 'Scams that use AI — cloned voices, deepfake videos, fake AI apps and investments — as police, regulators and consumer agencies warn about them, with who they target.',
  license: 'CC-BY-4.0',
  noun: { one: 'alert', other: 'alerts' },
  // One record per official page: a warning, a confirmed case or a set of official figures.
  identity: ['url'],
  fields: {
    title: {
      type: 'text',
      label: 'Alert',
      required: true,
      max: 160,
      help: 'What the page warns about or reports, in one short English line, e.g. "Scammers clone relatives’ voices to ask for bail money". Never include a person’s name.',
    },
    url: {
      type: 'url',
      label: 'Official page',
      required: true,
      help: 'The page of the police force, regulator, consumer agency, court or government body that issued it.',
    },
    scam_type: {
      type: 'enum',
      label: 'Scam type',
      required: true,
      help: 'voice-clone (a cloned voice on a call or message), deepfake-video (a faked face in a video call or video), deepfake-ad (a faked celebrity or official in an advert or post), fake-ai-investment (a scheme sold as AI trading or AI profits), fake-ai-tool (a fake AI app, site or download), ai-romance (AI-made personas, photos or chats for romance or sextortion), ai-phishing (AI-written messages or chatbots that steal data or money), other.',
      values: ['voice-clone', 'deepfake-video', 'deepfake-ad', 'fake-ai-investment', 'fake-ai-tool', 'ai-romance', 'ai-phishing', 'other'],
      valueLabels: {
        'voice-clone': 'Cloned voice',
        'deepfake-video': 'Deepfake video or call',
        'deepfake-ad': 'Deepfake ad or endorsement',
        'fake-ai-investment': 'Fake AI investment',
        'fake-ai-tool': 'Fake AI app or site',
        'ai-romance': 'AI romance or sextortion',
        'ai-phishing': 'AI phishing or chatbot',
        other: 'Other',
      },
    },
    kind: {
      type: 'enum',
      label: 'Kind',
      required: true,
      help: 'warning (an official alert or advice), case (a case the authority confirms: a report, an arrest, a charge or a ruling), statistics (official figures on AI scams).',
      values: ['warning', 'case', 'statistics'],
      valueLabels: { warning: 'Official warning', case: 'Confirmed case', statistics: 'Official figures' },
    },
    channel: {
      type: 'tags',
      label: 'How it reaches people',
      max: 4,
      help: 'The channels the page names: phone, video-call, messaging, social-media, email, ads, app-store, website.',
    },
    targets: {
      type: 'text',
      label: 'Who is targeted',
      max: 120,
      help: 'Who it targets when the page says, e.g. older people, job seekers or company finance staff.',
    },
    issuer: {
      type: 'text',
      label: 'Issued by',
      required: true,
      max: 120,
      help: 'The body that issued it, in English, e.g. Federal Bureau of Investigation or Hong Kong Police Force.',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Country or area',
      required: true,
      max: 3,
      help: 'Where the warning or case applies, in English, e.g. ["United States"] or ["Hong Kong"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    loss_usd: {
      type: 'number',
      label: 'Reported loss (USD)',
      min: 0,
      display: 'usd',
      help: 'The money lost as the page states it, in US dollars; convert other currencies at the day’s rate and put the original in Loss as stated.',
    },
    loss_stated: {
      type: 'text',
      label: 'Loss as stated',
      max: 60,
      help: 'The loss as the page writes it, e.g. HK$200 million or €1.2 million.',
    },
    published_on: { type: 'date', label: 'Published', required: true, help: 'The day the page was published.' },
  },
  accept: { published_on: { from: 'today-365', to: 'today' } },
  example: {
    data: {
      title: 'Scammers clone grandchildren’s voices to ask for bail money',
      url: 'https://example.org/alerts/voice-cloning',
      scam_type: 'voice-clone',
      kind: 'warning',
      channel: ['phone'],
      targets: 'older people',
      issuer: 'Example State Police',
      country: ['United States'],
      region: 'americas',
      published_on: '2026-09-15',
    },
    source_url: 'https://example.org/alerts/voice-cloning',
    evidence:
      'Scammers are using artificial intelligence to clone the voices of grandchildren and call grandparents asking for bail money, the Example State Police warned on September 15, 2026.',
  },
  table: {
    columns: ['title', 'scam_type', 'kind', 'issuer', 'country', 'published_on', 'loss_usd'],
    defaultSort: '-published_on',
    previewTitle: 'Latest alerts',
    previewColumns: ['title', 'scam_type', 'country', 'published_on'],
    fallback: { loss_usd: 'loss_stated' },
  },
  charts: [
    { kind: 'count', title: 'Alerts in the last 30 days', where: { published_on: { from: 'today-30' } } },
    { kind: 'over-time', title: 'Alerts by month', field: 'published_on', bucket: 'month' },
    { kind: 'by-category', title: 'By scam type', field: 'scam_type' },
    { kind: 'by-category', title: 'By kind', field: 'kind' },
    { kind: 'by-category', title: 'Top countries', field: 'country' },
    {
      kind: 'histogram',
      title: 'Reported loss (USD)',
      field: 'loss_usd',
      edges: [0, 10000, 100000, 1000000, 10000000, 100000000],
    },
  ],
  scope: {
    in: 'Scams that use AI — cloned voices, deepfake video or images, AI chatbots or AI-written messages, fake AI apps, tools and investment schemes — as warned about, confirmed or counted by a police force, regulator, consumer agency, court or government, published in the last 12 months.',
    out: 'Security companies’ marketing, research papers and blog posts; news reports with no official statement behind them; scams with no AI element; names, photos and other personal details of victims or suspects, which must never be recorded.',
  },
  sourceHints: [
    'Consumer agencies’ alerts, such as the FTC’s consumer alerts and Australia’s Scamwatch',
    'Police warnings, such as the FBI’s IC3 public service announcements, Europol, the Hong Kong Police Force’s Anti-Deception Coordination Centre and the Singapore Police Force',
    'Financial regulators’ warnings, such as the SEC, FINRA, the UK’s FCA and Australia’s ASIC',
    'Major news reports as leads: cite the official page when one exists',
  ],
  recheckAfterDays: 90,
  notify: { line: '{title} · {scam_type} · {country} · {published_on}' },
});
