import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'oncology-drug-updates',
  title: 'Cancer Drug Updates',
  description: 'Major cancer-drug events from regulators, trial registries and the companies behind them: Phase 3 results, approvals, accepted applications and safety notices — what was announced, by whom and when.',
  license: 'CC-BY-4.0',
  noun: { one: 'update', other: 'updates' },
  // One record per drug, kind of event, cancer type and day it was announced.
  identity: ['drug', 'event_type', 'cancer_type', 'announced_on'],
  fields: {
    drug: {
      type: 'text',
      label: 'Drug',
      required: true,
      max: 120,
      help: 'The generic (international nonproprietary) names only, as the source gives them, no brand names or codes, joined by " + " for a combination, e.g. "belzutifan + lenvatinib".',
    },
    company: {
      type: 'tags',
      names: true,
      label: 'Company',
      required: true,
      max: 3,
      help: 'The sponsor or marketing-authorization holder the source names, in English, e.g. ["Merck", "Moderna"].',
    },
    cancer_type: {
      type: 'enum',
      label: 'Cancer type',
      required: true,
      help: 'The group the indication belongs to; use any-solid-tumor for a tumor-agnostic indication and other when nothing fits.',
      values: [
        'lung',
        'breast',
        'prostate',
        'colorectal',
        'gastric-esophageal',
        'liver-biliary-pancreatic',
        'kidney-bladder',
        'gynecologic',
        'skin-melanoma',
        'head-neck-thyroid',
        'brain-nervous-system',
        'leukemia-lymphoma',
        'myeloma',
        'sarcoma',
        'any-solid-tumor',
        'other',
      ],
      valueLabels: {
        lung: 'Lung',
        breast: 'Breast',
        prostate: 'Prostate',
        colorectal: 'Colorectal',
        'gastric-esophageal': 'Gastric and esophageal',
        'liver-biliary-pancreatic': 'Liver, bile duct and pancreas',
        'kidney-bladder': 'Kidney and bladder',
        gynecologic: 'Ovarian, cervical and uterine',
        'skin-melanoma': 'Melanoma and skin',
        'head-neck-thyroid': 'Head, neck and thyroid',
        'brain-nervous-system': 'Brain and nervous system',
        'leukemia-lymphoma': 'Leukemia and lymphoma',
        myeloma: 'Myeloma',
        sarcoma: 'Sarcoma',
        'any-solid-tumor': 'Any solid tumor',
        other: 'Other',
      },
    },
    indication: {
      type: 'text',
      label: 'Indication',
      required: true,
      max: 200,
      help: 'The disease and treatment setting as the source words it, e.g. "Adjuvant treatment of completely resected stage IIB-IV melanoma".',
    },
    event_type: {
      type: 'enum',
      label: 'Event',
      required: true,
      help: 'phase3-results: the sponsor announced results of a Phase 3 trial. approval: a regulator approved the drug. application-accepted: a regulator accepted an application for review. safety-notice: a regulator or the sponsor announced a major safety action.',
      values: ['phase3-results', 'approval', 'application-accepted', 'safety-notice'],
      valueLabels: {
        'phase3-results': 'Phase 3 results',
        approval: 'Approval',
        'application-accepted': 'Application accepted',
        'safety-notice': 'Safety notice',
      },
    },
    authority: {
      type: 'enum',
      label: 'Regulator',
      help: 'The regulator that acted, for an approval, an accepted application or a safety notice. Leave out for Phase 3 results.',
      values: ['fda', 'ema', 'nmpa', 'pmda', 'health-canada', 'mhra', 'other-regulator'],
      valueLabels: {
        fda: 'US FDA',
        ema: 'EMA',
        nmpa: 'China NMPA',
        pmda: 'Japan PMDA',
        'health-canada': 'Health Canada',
        mhra: 'UK MHRA',
        'other-regulator': 'Other regulator',
      },
    },
    trial_phase: {
      type: 'enum',
      label: 'Trial phase',
      help: 'For Phase 3 results only: the phase the source gives. Leave out for other events.',
      values: ['phase-3', 'phase-2-3'],
      valueLabels: { 'phase-3': 'Phase 3', 'phase-2-3': 'Phase 2/3' },
    },
    trial_name: {
      type: 'text',
      label: 'Trial',
      max: 80,
      help: 'For Phase 3 results only: the trial\'s name as the source gives it, e.g. "INTerpath-001".',
    },
    nct_id: {
      type: 'text',
      label: 'ClinicalTrials.gov ID',
      max: 11,
      help: 'For Phase 3 results only: the ClinicalTrials.gov number the source states, NCT followed by 8 digits. Leave out when the source gives none.',
    },
    participants: {
      type: 'number',
      label: 'Participants',
      min: 1,
      max: 1000000,
      display: 'plain',
      help: 'For Phase 3 results only: the number of patients enrolled or randomized, exactly as the source states it. Leave out when it gives none.',
    },
    primary_endpoint: {
      type: 'enum',
      label: 'Primary endpoint',
      help: 'For Phase 3 results only: what the source says about the trial\'s primary endpoint. not-stated when it does not say.',
      values: ['met', 'not-met', 'not-stated'],
      valueLabels: { met: 'Met', 'not-met': 'Not met', 'not-stated': 'Not stated' },
    },
    announced_on: {
      type: 'date',
      label: 'Announced',
      required: true,
      help: 'The day the source says the regulator acted or the sponsor announced the result, e.g. the approval date on the FDA page or the date line of the press release.',
    },
    result_summary: {
      type: 'text',
      label: 'What was announced',
      required: true,
      max: 280,
      help: 'One plain sentence saying who announced what, in the source\'s own terms, e.g. "FDA approved examplimab for adults with ...". No opinion on benefit and no advice for patients.',
    },
    url: {
      type: 'url',
      label: 'Source page',
      required: true,
      help: 'The page that states the facts: the regulator\'s or registry\'s own page when there is one, otherwise the company\'s own release.',
    },
  },
  accept: { announced_on: { from: 'today-90', to: 'today' } },
  example: {
    data: {
      drug: 'examplimab',
      company: ['Example Pharma'],
      cancer_type: 'lung',
      indication: 'Previously untreated metastatic non-small cell lung cancer',
      event_type: 'phase3-results',
      trial_phase: 'phase-3',
      trial_name: 'EXAMPLE-01',
      nct_id: 'NCT00000000',
      participants: 600,
      primary_endpoint: 'met',
      announced_on: '2026-09-18',
      result_summary: 'Example Pharma announced that the Phase 3 EXAMPLE-01 trial of examplimab met its primary endpoint of overall survival.',
      url: 'https://example.org/news/example-01-topline',
    },
    source_url: 'https://example.org/news/example-01-topline',
    evidence:
      'September 18, 2026 - Example Pharma today announced that the Phase 3 EXAMPLE-01 trial of examplimab in 600 patients with previously untreated metastatic non-small cell lung cancer met its primary endpoint of overall survival.',
  },
  table: {
    columns: ['drug', 'company', 'cancer_type', 'event_type', 'authority', 'announced_on'],
    defaultSort: '-announced_on',
    previewTitle: 'Latest cancer-drug updates',
    previewColumns: ['drug', 'company', 'cancer_type', 'event_type', 'announced_on'],
  },
  charts: [
    { kind: 'count', title: 'Updates in the last 30 days', where: { announced_on: { from: 'today-30' } } },
    { kind: 'over-time', title: 'Updates by week', field: 'announced_on', bucket: 'week' },
    { kind: 'by-category', title: 'By event', field: 'event_type' },
    { kind: 'by-category', title: 'By cancer type', field: 'cancer_type' },
    { kind: 'by-category', title: 'By regulator', field: 'authority' },
    { kind: 'by-category', title: 'Top companies', field: 'company' },
    { kind: 'histogram', title: 'Phase 3 trial size', field: 'participants', edges: [100, 300, 600, 1000, 2000] },
  ],
  scope: {
    in: 'Announcements about cancer treatments (drugs, biologics, cell and gene therapies) made in the last 90 days: a sponsor\'s Phase 3 or Phase 2/3 trial results, a regulator\'s approval of a drug or a new indication, a regulator\'s acceptance of an application for review, and major safety notices such as a boxed warning, a safety communication, a clinical hold or a withdrawal from the market. Anywhere in the world.',
    out: 'Phase 1 and Phase 2 results; conference abstracts and subgroup analyses that follow an earlier announcement; non-cancer uses of cancer drugs; supportive care, diagnostics and devices; biosimilar and generic approvals; licensing, financing and merger deals; analyst opinions, price targets and any judgment of how well a drug works; news reports that give no regulator\'s or sponsor\'s statement.',
  },
  sourceHints: [
    'Regulators first: FDA oncology approval notifications and drug safety communications, EMA, NMPA, PMDA and the other regulators\' own announcements',
    'Trial registries and filings next: ClinicalTrials.gov records, and the sponsor\'s SEC 8-K filings on sec.gov',
    'The sponsor\'s own press release, on its website or through Business Wire, PR Newswire or GlobeNewswire',
    'Trade and news media only as leads; cite the primary page, and never a number that only a media report gives',
  ],
  recheckAfterDays: 30,
  notify: { line: '{drug} · {event_type} · {cancer_type} · {announced_on}' },
});
