import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'recalls',
  title: 'Product Recalls',
  description: 'Big recalls of cars and everyday products — 100,000 units or more — from safety regulators and makers: what is affected, the hazard and what owners get.',
  license: 'CC-BY-4.0',
  noun: { one: 'recall', other: 'recalls' },
  // One record per recall notice.
  identity: ['url'],
  fields: {
    product: {
      type: 'text',
      label: 'Product',
      required: true,
      max: 160,
      help: 'What is recalled, as the notice names it, e.g. "2022–2024 Example Motors Pathfinder SUVs" or "Example brand portable chargers".',
    },
    brand: {
      type: 'tags',
      names: true,
      label: 'Brand',
      required: true,
      max: 3,
      help: 'The brand or maker, in English, e.g. ["Ford"] or ["IKEA"].',
    },
    url: {
      type: 'url',
      label: 'Recall notice',
      required: true,
      help: 'The regulator’s recall notice, or the maker’s official recall page when no regulator page states the facts.',
    },
    category: {
      type: 'enum',
      label: 'Category',
      required: true,
      values: ['vehicle', 'child-product', 'household', 'appliance', 'electronics', 'toy', 'sports-outdoor', 'other'],
      valueLabels: {
        vehicle: 'Cars and motorcycles',
        'child-product': 'Baby and child products',
        household: 'Furniture and household',
        appliance: 'Appliances',
        electronics: 'Electronics and batteries',
        toy: 'Toys',
        'sports-outdoor': 'Sports and outdoor',
        other: 'Other',
      },
    },
    hazard: {
      type: 'enum',
      label: 'Hazard',
      required: true,
      help: 'The main hazard the notice names.',
      values: ['crash', 'fire', 'injury', 'choking', 'electric-shock', 'poisoning', 'tip-over', 'fall', 'other'],
      valueLabels: {
        crash: 'Crash',
        fire: 'Fire or burns',
        injury: 'Injury',
        choking: 'Choking',
        'electric-shock': 'Electric shock',
        poisoning: 'Poisoning',
        'tip-over': 'Tip-over',
        fall: 'Falls',
        other: 'Other',
      },
    },
    units: {
      type: 'number',
      label: 'Units',
      required: true,
      min: 100000,
      help: 'How many units the notice recalls, in its country. Recalls under 100,000 units are out of scope.',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Recalled in',
      required: true,
      max: 3,
      help: 'The country or area of the notice, in English, e.g. ["United States"] or ["European Union"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    remedy: {
      type: 'tags',
      label: 'Remedy',
      max: 3,
      help: 'What owners get, as the notice says: repair, refund, replacement, inspection or stop-use.',
    },
    regulator: {
      type: 'text',
      label: 'Regulator',
      max: 120,
      help: 'The regulator that published or oversees it, in English, e.g. US Consumer Product Safety Commission or NHTSA.',
    },
    announced_on: { type: 'date', label: 'Announced', required: true, help: 'The day the recall was announced.' },
  },
  accept: { announced_on: { from: 'today-90', to: 'today' } },
  example: {
    data: {
      product: 'Example brand 10,000 mAh portable chargers',
      brand: ['Example'],
      url: 'https://example.org/recalls/portable-chargers',
      category: 'electronics',
      hazard: 'fire',
      units: 250000,
      country: ['United States'],
      region: 'americas',
      remedy: ['refund'],
      regulator: 'US Consumer Product Safety Commission',
      announced_on: '2026-09-18',
    },
    source_url: 'https://example.org/recalls/portable-chargers',
    evidence:
      'About 250,000 Example brand 10,000 mAh portable chargers are recalled because the battery can overheat, posing a fire hazard. Consumers should stop using them and contact Example for a full refund.',
  },
  table: {
    columns: ['product', 'brand', 'category', 'hazard', 'units', 'country', 'announced_on'],
    defaultSort: '-announced_on',
    previewTitle: 'Latest recalls',
    previewColumns: ['product', 'brand', 'hazard', 'units', 'announced_on'],
  },
  charts: [
    { kind: 'count', title: 'Recalls in the last 30 days', where: { announced_on: { from: 'today-30' } } },
    { kind: 'over-time', title: 'Recalls by week', field: 'announced_on', bucket: 'week' },
    { kind: 'by-category', title: 'By category', field: 'category' },
    { kind: 'by-category', title: 'By hazard', field: 'hazard' },
    { kind: 'by-category', title: 'Top brands', field: 'brand' },
    { kind: 'histogram', title: 'Units recalled', field: 'units', edges: [100000, 250000, 500000, 1000000, 2500000] },
  ],
  scope: {
    in: 'Recalls of cars, motorcycles and everyday consumer products — 100,000 units or more in one notice — announced by a safety regulator, or by the maker on its official recall page, in the last 90 days, anywhere in the world.',
    out: 'Food, drink, medicines, medical devices and cosmetics; recalls under 100,000 units; industrial and commercial equipment; software updates that are not recalls; news reports that give no regulator’s or maker’s figures.',
  },
  sourceHints: [
    'Regulators’ recall notices, such as the US CPSC, Health Canada, product recalls on GOV.UK, Australia’s Product Safety and the EU’s Safety Gate',
    'Vehicle recalls from NHTSA, Transport Canada, the UK’s DVSA and China’s State Administration for Market Regulation, or the carmaker’s own announcement',
    'Major news agencies’ reports as leads, or as the source when they give the regulator’s figures',
  ],
  recheckAfterDays: 90,
  notify: { line: '{product} · {hazard} · {units} units · {country} · {announced_on}' },
});
