import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-data-centers',
  title: 'AI Data Centers',
  description: 'Data center campuses built for AI, announced worldwide since 2024: who builds them, where, and how much power.',
  license: 'CC-BY-4.0',
  noun: { one: 'project', other: 'projects' },
  // One record per campus. Names carry their site ("Stargate Abilene"), so one developer's
  // campuses stay apart; two names for one campus are merged by maintainers.
  identity: ['name'],
  fields: {
    name: {
      type: 'text',
      label: 'Project',
      required: true,
      max: 120,
      help: 'The project’s own name with its site when it has several, e.g. Stargate Abilene or Hyperion; when it has no name, the developer and the place, e.g. Google Kansas City.',
    },
    developer: {
      type: 'tags',
      names: true,
      label: 'Developer',
      required: true,
      max: 4,
      help: 'Who builds or owns it, as each names itself, e.g. ["Crusoe", "Blue Owl Capital"].',
    },
    tenant: {
      type: 'tags',
      names: true,
      label: 'Built for',
      max: 4,
      help: 'Who will use its compute, when the source names them, e.g. ["OpenAI"]. Leave it out when that is the developer itself.',
    },
    stage: {
      type: 'enum',
      label: 'Status',
      required: true,
      help: 'As of the source: announced (planned, not yet built), under construction, partly operational (some buildings or phases running), operational, paused or cancelled.',
      values: ['announced', 'under-construction', 'partly-operational', 'operational', 'paused', 'cancelled'],
      valueLabels: {
        announced: 'Announced',
        'under-construction': 'Under construction',
        'partly-operational': 'Partly operational',
        operational: 'Operational',
        paused: 'Paused',
        cancelled: 'Cancelled',
      },
    },
    capacity_mw: {
      type: 'number',
      label: 'Capacity (MW)',
      min: 0,
      unit: 'MW',
      help: 'Planned power capacity at full build-out, in megawatts (1 GW is 1000 MW), as the source states it.',
    },
    investment_usd: {
      type: 'number',
      label: 'Investment (USD)',
      min: 0,
      display: 'usd',
      help: 'The stated investment in the project, only when the source gives it in US dollars. Never convert it yourself.',
    },
    investment_stated: {
      type: 'text',
      label: 'Investment as stated',
      max: 80,
      help: 'When the source gives the investment in another currency or as a range, in its words, e.g. £10 billion.',
    },
    announced_on: {
      type: 'date',
      label: 'Announced',
      required: true,
      help: 'The day the project was first made public.',
    },
    city: {
      type: 'tags',
      names: true,
      label: 'Location',
      required: true,
      max: 3,
      help: 'The town or city it is in or nearest to, in English, e.g. ["Abilene"]; a county when the source names no town, e.g. ["Richland Parish"].',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Country',
      required: true,
      max: 1,
      help: 'The country it is in, in English, e.g. ["United States"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
  },
  accept: { announced_on: { from: '2024-01-01', to: 'today' } },
  example: {
    data: {
      name: 'Example Ridge AI Campus',
      developer: ['Example Compute'],
      tenant: ['Sample AI'],
      stage: 'under-construction',
      capacity_mw: 1200,
      investment_usd: 15000000000,
      announced_on: '2026-03-10',
      city: ['Springfield'],
      country: ['United States'],
      region: 'americas',
    },
    source_url: 'https://example.com/news/example-ridge-ai-campus',
    evidence:
      'Example Compute today broke ground on the Example Ridge AI Campus near Springfield, a 1.2 gigawatt data center built for Sample AI and an investment of $15 billion.',
  },
  table: {
    columns: ['name', 'developer', 'capacity_mw', 'investment_usd', 'stage', 'city', 'country', 'announced_on'],
    defaultSort: '-announced_on',
    previewTitle: 'Latest announcements',
    previewColumns: ['name', 'developer', 'capacity_mw', 'stage', 'country'],
    fallback: { investment_usd: 'investment_stated' },
  },
  charts: [
    { kind: 'count', title: 'Announced in the last 90 days', where: { announced_on: { from: 'today-90' } } },
    { kind: 'over-time', title: 'Announcements by month', field: 'announced_on', bucket: 'month' },
    { kind: 'by-category', title: 'By status', field: 'stage' },
    { kind: 'by-category', title: 'Top developers', field: 'developer' },
    { kind: 'by-category', title: 'Top countries', field: 'country' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    {
      kind: 'histogram',
      title: 'Capacity (MW)',
      field: 'capacity_mw',
      edges: [0, 100, 250, 500, 1000, 2000, 5000],
    },
  ],
  scope: {
    in: 'Data center campuses built mainly for AI training or inference, by AI labs, cloud and GPU cloud providers, chipmakers, energy companies or investors, announced since 2024 with at least 100 MW of planned capacity or at least $1 billion of stated investment.',
    out: 'General-purpose and colocation data centers with no stated AI focus; smaller projects; chip purchases and cloud contracts without a named site; chip plants and power plants on their own; projects only rumored or under consideration.',
  },
  sourceHints: [
    'Announcements by the developer, its partners or the local government',
    'Wire services such as Business Wire and PR Newswire',
    'Trade and business press such as Data Center Dynamics, Reuters and local newspapers',
  ],
  recheckAfterDays: 60,
  notify: { line: '{name} · {developer} · {capacity_mw} · {investment_usd} · {city} · {stage}' },
});
