import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-acquisitions',
  title: 'AI Acquisitions',
  description: 'AI companies bought, acqui-hired or licensed-and-hired, and what AI companies buy, with sources.',
  license: 'CC-BY-4.0',
  noun: { one: 'deal', other: 'deals' },
  // One deal per company bought. The website is cut to its home page, so variants of one
  // site compare equal.
  identity: ['website'],
  fields: {
    company: {
      type: 'text',
      label: 'Company acquired',
      required: true,
      max: 120,
      help: 'The company or team bought, as it names itself; when the source also gives a name in another script, add it in brackets.',
    },
    website: {
      type: 'url',
      label: 'Website',
      required: true,
      homePage: true,
      help: "The acquired company's own website, even when it now redirects to the buyer.",
    },
    acquirer: {
      type: 'tags',
      names: true,
      label: 'Acquirer',
      required: true,
      max: 3,
      help: 'The buyer as it names itself, e.g. ["Nvidia"]; two or three when they buy together. A subsidiary buys under its parent\'s name only when the source says so.',
    },
    deal_type: {
      type: 'enum',
      label: 'Deal',
      required: true,
      help: 'acquisition: the buyer takes the whole company. acqui-hire: the buyer hires the team and winds the product down. license-and-hire: the buyer licenses the technology and hires the founders or most staff while the company stays independent. merger: two companies combine. majority-stake: the buyer takes more than half.',
      values: ['acquisition', 'acqui-hire', 'license-and-hire', 'merger', 'majority-stake'],
      valueLabels: {
        acquisition: 'Acquisition',
        'acqui-hire': 'Acqui-hire',
        'license-and-hire': 'License and hire',
        merger: 'Merger',
        'majority-stake': 'Majority stake',
      },
    },
    focus: {
      type: 'text',
      label: 'What it builds',
      required: true,
      max: 140,
      help: 'A short phrase about the company acquired, e.g. Inference engine for open-weight models.',
    },
    sector: {
      type: 'enum',
      label: 'Sector',
      required: true,
      help: "The one sector the acquired company's main product fits best. Chips, compute, networking and data-center power are infrastructure; agents sold to businesses are enterprise unless a sector below fits better.",
      values: [
        'foundation-models',
        'infrastructure',
        'developer-tools',
        'security',
        'robotics',
        'health',
        'finance',
        'enterprise',
        'consumer',
        'defense',
        'other',
      ],
      valueLabels: {
        'foundation-models': 'Foundation models',
        infrastructure: 'Chips, cloud & data centers',
        'developer-tools': 'Developer & data tools',
        security: 'Security & governance',
        robotics: 'Robotics & physical AI',
        health: 'Health & life sciences',
        finance: 'Finance & insurance',
        enterprise: 'Business apps & agents',
        consumer: 'Consumer',
        defense: 'Defense & public sector',
        other: 'Other',
      },
    },
    announced_on: {
      type: 'date',
      label: 'Announced',
      required: true,
      help: 'The day the buyer, the company or the first news report made the deal public.',
    },
    price_usd: {
      type: 'number',
      label: 'Price (USD)',
      min: 0,
      display: 'usd',
      help: 'The price paid, only when the source states it in US dollars or gives its own conversion. Never convert or estimate it yourself.',
    },
    price_stated: {
      type: 'text',
      label: 'Price as stated',
      max: 80,
      help: 'When the source gives the price in another currency, as a range or as a valuation, in its words, e.g. €200 million or about $1 billion including stock.',
    },
    // Where the company bought is based. Optional: a small startup's city is often on no page,
    // and a deal is worth listing without it.
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      max: 3,
      help: 'The city the acquired company is headquartered in, in English, e.g. ["Paris"], when the source or the company\'s own site states it; two when it names two headquarters.',
    },
    country: {
      type: 'text',
      label: 'Country',
      max: 60,
      help: 'The country the acquired company is based in, e.g. France, when a page states it; two separated by a slash when the source names both.',
    },
    region: {
      type: 'enum',
      label: 'Region',
      help: "Where the acquired company's headquarters is, whenever its country is known; for two countries, the first.",
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
  },
  accept: { announced_on: { from: 'today-90', to: 'today' } },
  example: {
    data: {
      company: 'Example Vision',
      website: 'https://example.com/',
      acquirer: ['Sample Corp'],
      deal_type: 'acquisition',
      focus: 'Computer vision models for retail shelf analytics',
      sector: 'enterprise',
      announced_on: '2026-09-15',
      price_usd: 120000000,
      city: ['Austin'],
      country: 'United States',
      region: 'americas',
    },
    source_url: 'https://example.com/news/sample-corp-acquires-example-vision',
    evidence:
      'Sample Corp today announced that it has acquired Example Vision, an Austin-based maker of computer vision models for retail, for $120 million in cash.',
  },
  table: {
    columns: ['company', 'acquirer', 'deal_type', 'price_usd', 'announced_on', 'focus', 'city', 'country'],
    defaultSort: '-announced_on',
    previewTitle: 'Latest deals',
    previewColumns: ['company', 'acquirer', 'deal_type', 'price_usd', 'announced_on', 'city'],
    fallback: { price_usd: 'price_stated' },
  },
  charts: [
    { kind: 'count', title: 'Deals in the last 30 days', where: { announced_on: { from: 'today-30' } } },
    { kind: 'over-time', title: 'Deals by week announced', field: 'announced_on', bucket: 'week' },
    { kind: 'by-category', title: 'Top acquirers', field: 'acquirer' },
    { kind: 'by-category', title: 'By deal', field: 'deal_type' },
    { kind: 'by-category', title: 'By sector', field: 'sector' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'by-category', title: 'Top cities', field: 'city' },
    {
      kind: 'histogram',
      title: 'Price (USD)',
      field: 'price_usd',
      edges: [0, 10000000, 50000000, 100000000, 250000000, 500000000, 1000000000, 5000000000],
    },
  ],
  scope: {
    in: 'Deals that buy a company whose main product is AI, or the chips, cloud, data centers or data tools built for it, and any company bought by an AI lab or an AI-first company: acquisitions, acqui-hires, license-and-hire deals, mergers and majority stakes, signed or completed and announced in the last 90 days.',
    out: 'Rumors, talks and offers without a signed agreement; minority investments (they belong in AI Company Fundraising); IPOs and SPAC listings; companies that only use AI as a feature, unless the buyer is an AI company; purchases of patents, domains or assets alone.',
  },
  sourceHints: [
    "The buyer's or the acquired company's announcement, blog or newsroom",
    'Wire services such as Business Wire and PR Newswire',
    'Business and tech press such as TechCrunch, Reuters and 36Kr',
  ],
  recheckAfterDays: 90,
  notify: { line: '{company} · {deal_type} by {acquirer} · {price_usd} · {city} · {sector}' },
});
