import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-hackathons',
  title: 'AI Hackathons',
  description: 'Upcoming AI hackathons, online and in person.',
  license: 'CC-BY-4.0',
  noun: { one: 'hackathon', other: 'hackathons' },
  identity: ['url'],
  fields: {
    name: { type: 'text', label: 'Name', required: true, max: 160 },
    organizer: { type: 'text', label: 'Organizer', required: true, max: 120 },
    url: {
      type: 'url',
      label: 'Official page',
      required: true,
      help: 'The page people register on, run by the organizer or its registration platform.',
    },
    deadline: {
      type: 'date',
      label: 'Deadline',
      required: true,
      help: 'The last day to register; else the last day to submit; else the last day of the event.',
    },
    starts_on: { type: 'date', label: 'Starts', required: true },
    ends_on: { type: 'date', label: 'Ends', required: true },
    format: {
      type: 'enum',
      label: 'Format',
      required: true,
      values: ['online', 'in-person', 'hybrid'],
      valueLabels: { online: 'Online', 'in-person': 'In person', hybrid: 'Hybrid' },
    },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      max: 8,
      help: 'For in-person and hybrid hackathons: each city it takes place in, in English, e.g. ["San Francisco"] or ["Rome", "Milan"]. Leave out for online-only events.',
    },
    region: {
      type: 'enum',
      label: 'Region',
      help: 'Where it takes place; global when anyone anywhere can take part online.',
      values: ['global', 'americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        global: 'Global',
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    prize_usd: {
      type: 'number',
      label: 'Prize pool (USD)',
      min: 0,
      display: 'usd',
      help: 'Total cash prizes, only when the page states them in US dollars.',
    },
    tags: { type: 'tags', label: 'Tags', max: 8, help: 'Themes such as agents, llm or robotics.' },
  },
  rules: [
    { field: 'ends_on', notBefore: 'starts_on' },
    { field: 'ends_on', notBefore: 'deadline' },
  ],
  accept: { deadline: { from: 'today' } },
  example: {
    data: {
      name: 'Example Agents Hackathon',
      organizer: 'Example Labs',
      url: 'https://example.org/agents-hackathon',
      deadline: '2026-11-15',
      starts_on: '2026-11-21',
      ends_on: '2026-11-23',
      format: 'hybrid',
      city: ['San Francisco'],
      region: 'americas',
      prize_usd: 25000,
      tags: ['agents', 'llm'],
    },
    source_url: 'https://example.org/agents-hackathon',
    evidence:
      'Registration closes on November 15, 2026. The hackathon runs from November 21 to 23 in San Francisco and online, with $25,000 in prizes.',
  },
  table: {
    columns: ['name', 'organizer', 'deadline', 'starts_on', 'format', 'city', 'region', 'prize_usd'],
    defaultSort: 'deadline',
    defaultFilter: { deadline: { from: 'today' } },
    previewTitle: 'Closing soon',
    previewColumns: ['name', 'deadline', 'starts_on', 'format', 'city'],
  },
  charts: [
    { kind: 'count', title: 'Open for entries', where: { deadline: { from: 'today' } } },
    { kind: 'over-time', title: 'Hackathons by start week', field: 'starts_on', bucket: 'week' },
    { kind: 'by-category', title: 'By format', field: 'format' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'by-category', title: 'Top cities', field: 'city' },
    {
      kind: 'histogram',
      title: 'Prize pool (USD)',
      field: 'prize_usd',
      edges: [0, 1000, 5000, 10000, 25000, 50000, 100000],
    },
  ],
  scope: {
    in: 'AI-focused hackathons that anyone, or any student, can enter — online, in person or hybrid — with a deadline on or after today.',
    out: 'Grants, bounties and accelerators; events limited to one company, school, invite list or age group (a minimum age of 18 alone is fine); past events; recruiting events; paid courses.',
  },
  sourceHints: ['Organizer websites', 'Official announcements from AI labs, companies and communities'],
  recheckAfterDays: 14,
  notify: { line: '{name} · {format} · {city} · deadline {deadline}' },
});
