import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'scholarships',
  title: 'International Scholarships',
  description: 'Funded scholarships for studying abroad, from governments, universities and foundations, open for applications now: who can apply, what they pay and when they close.',
  license: 'CC-BY-4.0',
  noun: { one: 'scholarship', other: 'scholarships' },
  // One record per scholarship page. When the next round opens on the same page, the record
  // is corrected rather than added again.
  identity: ['url'],
  fields: {
    name: {
      type: 'text',
      label: 'Scholarship',
      required: true,
      max: 140,
      help: 'Its name as the page writes it, without the year, e.g. Chevening Scholarships or Erasmus Mundus Joint Masters.',
    },
    url: {
      type: 'url',
      label: 'Official page',
      required: true,
      help: 'The scholarship’s own page on the funder’s site.',
    },
    provider: {
      type: 'text',
      label: 'Funded by',
      required: true,
      max: 120,
      help: 'Who pays for it, in English, e.g. UK Government (FCDO), DAAD or Gates Cambridge Trust.',
    },
    funder_type: {
      type: 'enum',
      label: 'Funder',
      required: true,
      values: ['government', 'university', 'foundation', 'international'],
      valueLabels: {
        government: 'Government',
        university: 'University',
        foundation: 'Foundation or company',
        international: 'International organisation',
      },
    },
    host_country: {
      type: 'tags',
      names: true,
      label: 'Study in',
      required: true,
      max: 5,
      help: 'Where the study takes place, in English, e.g. ["United Kingdom"]; a group name when the page uses one, e.g. ["Europe"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      help: 'Where the study takes place; the first when there are several.',
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    level: {
      type: 'tags',
      label: 'Level',
      required: true,
      max: 4,
      help: 'What it funds: bachelor, master, phd, postdoc, short-course or language.',
    },
    coverage: {
      type: 'enum',
      label: 'Coverage',
      required: true,
      help: 'full when the page says it covers tuition and living costs; partial otherwise.',
      values: ['full', 'partial'],
      valueLabels: { full: 'Fully funded', partial: 'Partly funded' },
    },
    value_stated: {
      type: 'text',
      label: 'What it pays',
      max: 160,
      help: 'What it pays as the page writes it, e.g. "Tuition, a monthly stipend of £1,347 and return flights".',
    },
    eligibility: {
      type: 'text',
      label: 'Who can apply',
      max: 200,
      help: 'Who can apply as the page says, e.g. "Citizens of Chevening-eligible countries with two years of work experience".',
    },
    opens_on: { type: 'date', label: 'Opens', help: 'The first day to apply, when the page states it.' },
    deadline: {
      type: 'date',
      label: 'Deadline',
      required: true,
      help: 'The last day to apply for the next round; the earliest when it differs by country.',
    },
  },
  rules: [{ field: 'deadline', notBefore: 'opens_on' }],
  accept: { deadline: { from: 'today' } },
  example: {
    data: {
      name: 'Example Government Scholarships',
      url: 'https://example.org/scholarships',
      provider: 'Example Ministry of Education',
      funder_type: 'government',
      host_country: ['Example Republic'],
      region: 'europe',
      level: ['master'],
      coverage: 'full',
      value_stated: 'Tuition, a monthly stipend of €1,200 and return flights',
      eligibility: 'Graduates from any country except the Example Republic',
      opens_on: '2026-09-01',
      deadline: '2026-11-15',
    },
    source_url: 'https://example.org/scholarships',
    evidence:
      'Example Government Scholarships cover tuition, a monthly stipend of €1,200 and return flights for a master’s degree. Applications open on 1 September 2026 and close on 15 November 2026.',
  },
  table: {
    columns: ['name', 'provider', 'host_country', 'level', 'coverage', 'deadline'],
    defaultSort: 'deadline',
    defaultFilter: { deadline: { from: 'today' } },
    previewTitle: 'Closing soon',
    previewColumns: ['name', 'host_country', 'level', 'coverage', 'deadline'],
  },
  charts: [
    { kind: 'count', title: 'Open for applications', where: { deadline: { from: 'today' } } },
    { kind: 'over-time', title: 'Deadlines by month', field: 'deadline', bucket: 'month' },
    { kind: 'by-category', title: 'Top places to study', field: 'host_country' },
    { kind: 'by-category', title: 'By level', field: 'level' },
    { kind: 'by-category', title: 'By coverage', field: 'coverage' },
    { kind: 'by-category', title: 'By funder', field: 'funder_type' },
  ],
  scope: {
    in: 'Scholarships that pay for students to study in another country — for a degree, a research post or a non-degree program — from governments, universities, foundations, companies or international organisations, with an application deadline on or after today.',
    out: 'Loans; awards only for a country’s own citizens studying at home; fee discounts alone; prizes and competitions; one-off travel or conference grants; aggregator, agent and forum pages as sources.',
  },
  sourceHints: [
    'The funder’s own scholarship page',
    'Government study-abroad portals, such as Study in the UK, DAAD, Study in Japan and Campus China',
    'Universities’ scholarship pages for international students',
  ],
  recheckAfterDays: 30,
  notify: { line: '{name} · {host_country} · {level} · {coverage} · deadline {deadline}' },
});
