import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'marathons',
  title: 'World Marathons',
  description: 'Upcoming marathons around the world with an international or national label: dates, places and registration.',
  license: 'CC-BY-4.0',
  noun: { one: 'marathon', other: 'marathons' },
  // One record per edition: a race's website stays the same every year, its race day does not.
  identity: ['url', 'race_date'],
  fields: {
    name: {
      type: 'text',
      label: 'Marathon',
      required: true,
      max: 140,
      help: 'The race’s official name in English as its site writes it, e.g. BMW Berlin Marathon; when the site also gives a name in another script, add it in brackets, e.g. Shanghai Marathon (上海马拉松).',
    },
    url: { type: 'url', label: 'Website', required: true, homePage: true, help: 'The race’s official website.' },
    race_date: { type: 'date', label: 'Race day', required: true, help: 'The day the marathon is run.' },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      required: true,
      max: 2,
      help: 'The city it starts in, in English, e.g. ["Berlin"]; two when it runs from one to another.',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Country or area',
      required: true,
      max: 1,
      help: 'The country or area as World Athletics names it, in English, e.g. ["Germany"], ["Hong Kong"] or ["Chinese Taipei"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    label: {
      type: 'enum',
      label: 'Label',
      required: true,
      help: 'The highest it holds, as a page states it: world-major (an Abbott World Marathon Major), then the World Athletics label (platinum, gold, elite or label), then aims (an AIMS member race), then national (a national athletics federation’s top label, such as the Chinese Athletics Association’s gold or platinum label).',
      values: ['world-major', 'platinum', 'gold', 'elite', 'label', 'aims', 'national'],
      valueLabels: {
        'world-major': 'World Marathon Major',
        platinum: 'World Athletics Platinum',
        gold: 'World Athletics Gold',
        elite: 'World Athletics Elite',
        label: 'World Athletics Label',
        aims: 'AIMS member',
        national: 'National label',
      },
    },
    registration_closes: {
      type: 'date',
      label: 'Registration closes',
      help: 'The last day to register or to enter the ballot, when the page states one.',
    },
    entry_fee: {
      type: 'text',
      label: 'Entry fee',
      max: 60,
      help: 'The marathon entry fee as the page writes it, e.g. €139 or ¥200; the standard fee when there are several.',
    },
    field_size: {
      type: 'number',
      label: 'Field size',
      min: 0,
      help: 'The number of marathon places, or last edition’s marathon finishers, when the page states it.',
    },
    distances: {
      type: 'tags',
      label: 'Other races',
      max: 6,
      help: 'Other races held with it, e.g. half-marathon, 10k, 5k, relay, wheelchair.',
    },
  },
  rules: [{ field: 'race_date', notBefore: 'registration_closes' }],
  accept: { race_date: { from: 'today', to: 'today+400' } },
  example: {
    data: {
      name: 'Example City Marathon',
      url: 'https://example.org/',
      race_date: '2027-04-18',
      city: ['Springfield'],
      country: ['United States'],
      region: 'americas',
      label: 'gold',
      registration_closes: '2027-03-31',
      entry_fee: '$145',
      field_size: 20000,
      distances: ['half-marathon', '5k'],
    },
    source_url: 'https://example.org/',
    evidence:
      'The Example City Marathon, a World Athletics Gold Label Road Race, starts on Sunday, April 18, 2027. Registration for the 20,000 places closes on March 31, 2027.',
  },
  table: {
    columns: ['name', 'race_date', 'city', 'country', 'label', 'registration_closes', 'field_size'],
    defaultSort: 'race_date',
    defaultFilter: { race_date: { from: 'today' } },
    previewTitle: 'Next marathons',
    previewColumns: ['name', 'race_date', 'city', 'country', 'label'],
  },
  charts: [
    { kind: 'count', title: 'Upcoming marathons', where: { race_date: { from: 'today' } } },
    { kind: 'over-time', title: 'Marathons by month', field: 'race_date', bucket: 'month' },
    { kind: 'by-category', title: 'By label', field: 'label' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'by-category', title: 'Top countries', field: 'country' },
    { kind: 'histogram', title: 'Field size', field: 'field_size', edges: [0, 1000, 5000, 10000, 20000, 40000] },
  ],
  scope: {
    in: 'Full marathons (42.195 km road races) anywhere in the world, run on or after today, that are an Abbott World Marathon Major, hold a World Athletics label, are AIMS members, or hold a national athletics federation’s top label.',
    out: 'Half marathons, ultramarathons and trail races on their own; virtual races; marathons with none of those labels; past editions; fun runs.',
  },
  sourceHints: [
    'The race’s official website',
    'The World Athletics label road race calendar and the AIMS calendar, as leads: cite the race’s own page',
    'National federation calendars, such as the Chinese Athletics Association’s',
  ],
  recheckAfterDays: 30,
  notify: { line: '{name} · {race_date} · {city} · {country} · {label}' },
});
