import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'new-rules',
  title: 'New Rules Taking Effect',
  description: 'National laws and rules that change everyday life — money, work, driving, travel, health, online life — and the day each one takes effect.',
  license: 'CC-BY-4.0',
  noun: { one: 'rule', other: 'rules' },
  // One record per rule and start date: a rule that starts in stages has one record per stage.
  identity: ['title', 'effective_on'],
  fields: {
    title: {
      type: 'text',
      label: 'Rule',
      required: true,
      max: 160,
      help: 'The rule’s official name in English, or an English translation of it; add the original in brackets when it is in another script, e.g. Road Traffic Safety Law, amended (道路交通安全法).',
    },
    what_changes: {
      type: 'text',
      label: 'What changes',
      required: true,
      max: 280,
      help: 'In one plain English sentence, what changes for people, as the page states it, e.g. "Drivers may no longer hold a phone while driving, and the fine rises to ¥200."',
    },
    jurisdiction: {
      type: 'tags',
      names: true,
      label: 'Where',
      required: true,
      max: 1,
      help: 'The country, or the European Union, in English, e.g. ["China"], ["European Union"] or ["United Kingdom"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    topic: {
      type: 'enum',
      label: 'Topic',
      required: true,
      values: [
        'money-tax',
        'work-pay',
        'social-security',
        'driving-transport',
        'travel-immigration',
        'health',
        'consumer',
        'online-privacy',
        'housing',
        'family-education',
        'environment',
        'public-safety',
        'other',
      ],
      valueLabels: {
        'money-tax': 'Money and tax',
        'work-pay': 'Work and pay',
        'social-security': 'Pensions and social security',
        'driving-transport': 'Driving and transport',
        'travel-immigration': 'Travel and immigration',
        health: 'Health',
        consumer: 'Consumer rights',
        'online-privacy': 'Online life and privacy',
        housing: 'Housing',
        'family-education': 'Family and schooling',
        environment: 'Environment',
        'public-safety': 'Public safety',
        other: 'Other',
      },
    },
    effective_on: { type: 'date', label: 'Takes effect', required: true, help: 'The day it takes effect.' },
    issuer: {
      type: 'text',
      label: 'Issued by',
      required: true,
      max: 120,
      help: 'The body that made it, in English, e.g. State Council of China, UK Parliament or European Parliament and Council.',
    },
    url: {
      type: 'url',
      label: 'Official text',
      required: true,
      help: 'The official text, or the government’s own page about it.',
    },
  },
  accept: { effective_on: { from: 'today-30', to: 'today+365' } },
  example: {
    data: {
      title: 'Consumer Rights (Subscriptions) Act',
      what_changes: 'Companies must let customers cancel a subscription online as easily as they signed up, and remind them before a free trial turns into a paid plan.',
      jurisdiction: ['Example Republic'],
      region: 'europe',
      topic: 'consumer',
      effective_on: '2026-12-01',
      issuer: 'Parliament of the Example Republic',
      url: 'https://example.org/laws/subscriptions',
    },
    source_url: 'https://example.org/laws/subscriptions',
    evidence:
      'From 1 December 2026, companies must let customers cancel a subscription online as easily as they signed up, and must remind them before a free trial turns into a paid plan.',
  },
  table: {
    columns: ['title', 'jurisdiction', 'topic', 'effective_on', 'what_changes'],
    defaultSort: 'effective_on',
    defaultFilter: { effective_on: { from: 'today' } },
    previewTitle: 'Taking effect next',
    previewColumns: ['title', 'jurisdiction', 'topic', 'effective_on'],
  },
  charts: [
    { kind: 'count', title: 'Taking effect in the next 30 days', where: { effective_on: { from: 'today', to: 'today+30' } } },
    { kind: 'over-time', title: 'Rules by month they take effect', field: 'effective_on', bucket: 'month' },
    { kind: 'by-category', title: 'By topic', field: 'topic' },
    { kind: 'by-category', title: 'By country', field: 'jurisdiction' },
    { kind: 'by-category', title: 'By region', field: 'region' },
  ],
  scope: {
    in: 'Laws, regulations and official rules of a national government, or of the European Union, that change everyday life for ordinary people — money and tax, work and pay, pensions and social security, driving and transport, travel, health, consumer rights, online life and privacy, housing, family and schooling — taking effect in the last 30 days or the next 12 months.',
    out: 'Rules that only affect businesses or one industry; provincial, state and city rules; drafts and proposals not yet adopted; court rulings; tariffs and trade measures; rules whose start date no official page states.',
  },
  sourceHints: [
    'Governments’ official pages and gazettes, such as gov.cn and npc.gov.cn for China, legislation.gov.uk and GOV.UK, the US Federal Register, EUR-Lex and the European Commission',
    'State news agencies’ reports that quote the rule and its start date, such as Xinhua',
    'Monthly round-ups of new rules as leads: cite each rule’s own page',
  ],
  recheckAfterDays: 60,
  notify: { line: '{title} · {jurisdiction} · {topic} · from {effective_on}' },
});
