import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'robotaxis',
  title: 'Robotaxi Cities',
  description: 'Where you can ride a robotaxi: driverless taxi services city by city, from announced launches and public trials to rides with no one at the wheel.',
  license: 'CC-BY-4.0',
  noun: { one: 'service city', other: 'service cities' },
  // One record per service and city. When a service reaches its next stage in a city, the
  // record is corrected rather than added again.
  identity: ['service', 'city'],
  fields: {
    service: {
      type: 'tags',
      names: true,
      label: 'Service',
      required: true,
      max: 1,
      help: 'The robotaxi service as its operator names it in English, e.g. ["Waymo"], ["Apollo Go"], ["Pony.ai"], ["WeRide"], ["Zoox"] or ["Tesla Robotaxi"].',
    },
    company: {
      type: 'text',
      label: 'Company',
      max: 80,
      help: 'The company that runs it when its name differs from the service, e.g. Baidu for Apollo Go.',
    },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      required: true,
      max: 1,
      help: 'The main city of the service area, in English, e.g. ["Phoenix"] for the Phoenix area or ["Wuhan"].',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Country or area',
      required: true,
      max: 1,
      help: 'The country or area in English, e.g. ["United States"], ["China"] or ["United Arab Emirates"].',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    stage: {
      type: 'enum',
      label: 'Stage',
      required: true,
      help: 'The furthest stage a page confirms in this city: announced (a launch is announced for a stated date, month or year), testing (vehicles drive on public roads but the public cannot ride), safety-driver (the public can ride with an employee on board), driverless (the public can ride with no one in the driver’s seat, free or paid).',
      values: ['announced', 'testing', 'safety-driver', 'driverless'],
      valueLabels: {
        announced: 'Announced',
        testing: 'Testing, no public rides',
        'safety-driver': 'Public rides with a safety driver',
        driverless: 'Public rides, no one at the wheel',
      },
    },
    since: {
      type: 'date',
      label: 'Since',
      required: true,
      help: 'The day the current stage began, or the planned launch day when it is announced; the first of the month when a page gives only the month, e.g. 2026-06-01 for June 2026, and January 1 when it gives only the year.',
    },
    access: {
      type: 'enum',
      label: 'Who can ride',
      help: 'open (anyone can book), waitlist (sign up and wait), limited (selected riders, employees or an invite-only program).',
      values: ['open', 'waitlist', 'limited'],
      valueLabels: { open: 'Anyone', waitlist: 'Waitlist', limited: 'Selected riders' },
    },
    booking: {
      type: 'tags',
      names: true,
      label: 'How to book',
      max: 3,
      help: 'The apps that book it, e.g. ["Waymo app"], ["Uber"], ["Lyft"] or ["Apollo Go app"].',
    },
    area: {
      type: 'text',
      label: 'Service area',
      max: 200,
      help: 'Where in the city it runs, as the page says, e.g. "Downtown, Midtown and the airport" or "about 90 square miles".',
    },
    vehicles: {
      type: 'number',
      label: 'Vehicles',
      min: 0,
      help: 'The size of its fleet in this city, when a page states it.',
    },
  },
  example: {
    data: {
      service: ['Example Robotaxi'],
      company: 'Example Mobility',
      city: ['Springfield'],
      country: ['United States'],
      region: 'americas',
      stage: 'driverless',
      since: '2026-06-24',
      access: 'open',
      booking: ['Example app'],
      area: 'about 90 square miles',
      vehicles: 200,
    },
    source_url: 'https://example.org/blog/springfield',
    evidence:
      'Starting today, June 24, 2026, anyone in Springfield can hail a fully autonomous ride with no one behind the wheel on the Example app, across about 90 square miles with a fleet of 200 vehicles.',
  },
  table: {
    columns: ['service', 'city', 'country', 'stage', 'since', 'access', 'booking', 'vehicles'],
    defaultSort: '-since',
    previewTitle: 'Latest milestones',
    previewColumns: ['service', 'city', 'country', 'stage', 'since'],
  },
  charts: [
    { kind: 'count', title: 'Service cities' },
    { kind: 'by-category', title: 'By stage', field: 'stage' },
    { kind: 'by-category', title: 'Top services', field: 'service' },
    { kind: 'by-category', title: 'Top countries', field: 'country' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'over-time', title: 'Milestones by month', field: 'since', bucket: 'month' },
  ],
  scope: {
    in: 'Robotaxi services — cars that carry members of the public with no human driver in control, or that are tested for that on public roads — in a named city: from a launch announced for a stated time to public rides with no one at the wheel, anywhere in the world. Services booked through partners such as Uber or Lyft count.',
    out: 'Driverless buses and shuttles on fixed routes, trucks, delivery robots and privately owned cars with driver assistance; tests on closed tracks; services that have ended in that city; plans with no city or no time.',
  },
  sourceHints: [
    'The operator’s own announcements, blog and newsroom',
    'Regulators’ permits and notices, such as the California DMV and CPUC, and city and national transport authorities',
    'Ride-hailing partners’ announcements, such as Uber and Lyft',
    'Major news reports as leads: cite the operator’s or the regulator’s page when it states the facts',
  ],
  recheckAfterDays: 30,
  notify: { line: '{service} · {city} · {country} · {stage} · since {since}' },
});
