import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'ai-conferences',
  title: 'AI Conferences & CFPs',
  description: 'AI research and industry conferences worldwide, with their dates, places and calls for papers or talks.',
  license: 'CC-BY-4.0',
  noun: { one: 'conference', other: 'conferences' },
  // One record per edition. Names carry the year ("NeurIPS 2026"), because many series reuse
  // one website for every edition.
  identity: ['name'],
  fields: {
    name: {
      type: 'text',
      label: 'Conference',
      required: true,
      max: 160,
      help: 'Its short name and the year of this edition, as the page writes them, e.g. NeurIPS 2026 or AI Engineer World’s Fair 2026.',
    },
    organizer: { type: 'text', label: 'Organizer', max: 120, help: 'Who runs it, when the page says.' },
    url: {
      type: 'url',
      label: 'Official page',
      required: true,
      help: 'The page of this edition when it has one, else the conference’s own website.',
    },
    kind: {
      type: 'enum',
      label: 'Kind',
      required: true,
      help: 'research: peer-reviewed papers (academic conferences). developer: talks and workshops for people who build with AI. industry: business, product and executive events, expos and summits.',
      values: ['research', 'developer', 'industry'],
      valueLabels: { research: 'Research', developer: 'Developer', industry: 'Industry' },
    },
    starts_on: {
      type: 'date',
      label: 'Starts',
      required: true,
      help: 'The first day of the event, workshop and tutorial days included.',
    },
    ends_on: { type: 'date', label: 'Ends', required: true, help: 'The last day of the event, workshop days included.' },
    format: {
      type: 'enum',
      label: 'Format',
      required: true,
      values: ['in-person', 'online', 'hybrid'],
      valueLabels: { 'in-person': 'In person', online: 'Online', hybrid: 'Hybrid' },
    },
    city: {
      type: 'tags',
      names: true,
      label: 'City',
      max: 3,
      help: 'For in-person and hybrid conferences, the city it takes place in, in English, e.g. ["Vancouver"]. Leave it out for online-only ones.',
    },
    country: {
      type: 'tags',
      names: true,
      label: 'Country',
      max: 1,
      help: 'The country it takes place in, in English, e.g. ["Canada"]. Leave it out for online-only ones.',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      help: 'Where it takes place; global for online-only conferences.',
      values: ['global', 'americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        global: 'Global',
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
    cfp_deadline: {
      type: 'date',
      label: 'CFP deadline',
      help: 'The first deadline of the main call for papers or talks, as the page states it (abstract registration when one is required), also when it has passed. Leave it out when the conference has no call or the page gives no date.',
    },
    cfp_url: { type: 'url', label: 'Call for papers', help: 'The page of the call for papers or talks.' },
    topics: {
      type: 'tags',
      label: 'Topics',
      max: 6,
      help: 'Main themes as short tags. Use these when they fit: agents, llm, genai, machine-learning, computer-vision, nlp, speech, robotics, ml-systems, mlops, ai-coding, ai-safety, ai-governance, data-mining, information-retrieval, multimodal, enterprise-ai.',
    },
    attendees: {
      type: 'number',
      label: 'Attendees',
      min: 0,
      help: 'Expected or last edition’s attendance, only when the page states a number; the lower figure of a range.',
    },
  },
  rules: [{ field: 'ends_on', notBefore: 'starts_on' }],
  accept: { ends_on: { from: 'today' } },
  example: {
    data: {
      name: 'Example AI Summit 2027',
      organizer: 'Example Events',
      url: 'https://example.org/summit-2027',
      kind: 'industry',
      starts_on: '2027-03-10',
      ends_on: '2027-03-11',
      format: 'in-person',
      city: ['Berlin'],
      country: ['Germany'],
      region: 'europe',
      cfp_deadline: '2026-12-01',
      cfp_url: 'https://example.org/summit-2027/call-for-talks',
      topics: ['llm', 'agents'],
      attendees: 3000,
    },
    source_url: 'https://example.org/summit-2027',
    evidence:
      'Example AI Summit 2027 takes place on 10 and 11 March 2027 in Berlin, with more than 3,000 attendees. Our call for talks is open until 1 December 2026.',
  },
  table: {
    columns: ['name', 'kind', 'starts_on', 'cfp_deadline', 'format', 'city', 'country', 'region'],
    defaultSort: 'starts_on',
    defaultFilter: { ends_on: { from: 'today' } },
    previewTitle: 'Coming up',
    previewColumns: ['name', 'kind', 'starts_on', 'cfp_deadline', 'city'],
  },
  charts: [
    { kind: 'count', title: 'Upcoming conferences', where: { ends_on: { from: 'today' } } },
    { kind: 'count', title: 'Calls for papers open', where: { cfp_deadline: { from: 'today' } } },
    { kind: 'over-time', title: 'Conferences by month', field: 'starts_on', bucket: 'month' },
    { kind: 'by-category', title: 'By kind', field: 'kind' },
    { kind: 'by-category', title: 'By region', field: 'region' },
    { kind: 'by-category', title: 'Top topics', field: 'topics' },
    { kind: 'by-category', title: 'Top cities', field: 'city' },
    { kind: 'histogram', title: 'Attendees', field: 'attendees', edges: [0, 500, 1000, 5000, 10000, 50000] },
  ],
  scope: {
    in: 'Conferences, summits and symposia about AI or machine learning, research or industry, in any country or online, that end on or after today, with their calls for papers or talks when they have one.',
    out: 'Hackathons (they belong in AI Hackathons); meetups, webinars and talks shorter than a day; one company’s product launches; trade shows without an AI focus; workshops held inside a bigger conference (list the main conference); paid courses.',
  },
  sourceHints: [
    'Official conference websites and their call-for-papers pages',
    'Deadline trackers such as aideadlin.es and WikiCFP, as leads only: cite the conference’s own page',
    'Organizers’ announcements',
  ],
  recheckAfterDays: 30,
  notify: { line: '{name} · {kind} · {starts_on} · {city} · CFP {cfp_deadline}' },
});
