import { defineDataApp } from '../../src/shared/data-app.ts';

export default defineDataApp({
  slug: 'visa-changes',
  title: 'Visa Policy Changes',
  description: 'Who can now visit where without a visa, and where a visa or travel authorisation is newly needed: changes governments have announced, with the days they apply.',
  license: 'CC-BY-4.0',
  noun: { one: 'change', other: 'changes' },
  // One record per destination, kind of change and first day. One announcement can hold
  // several; travellers from more countries on the same terms share one record.
  identity: ['destination', 'change', 'effective_on'],
  fields: {
    title: {
      type: 'text',
      label: 'Change',
      required: true,
      max: 160,
      help: 'The change in one short English line, e.g. "China extends 30-day visa-free entry for nine European countries to the end of 2026".',
    },
    destination: {
      type: 'tags',
      names: true,
      label: 'Destination',
      required: true,
      max: 1,
      help: 'The country or area travellers visit, in English, e.g. ["China"], ["United Kingdom"] or ["Schengen Area"].',
    },
    travelers: {
      type: 'tags',
      names: true,
      label: 'Travellers from',
      required: true,
      max: 60,
      help: 'The nationalities it applies to, in English, e.g. ["Australia", "New Zealand"]; a group name when the page uses one, e.g. ["EU member states"]; ["All nationalities"] when it applies to every visitor.',
    },
    change: {
      type: 'enum',
      label: 'Kind of change',
      required: true,
      help: 'visa-free (entry without a visa starts or is extended), visa-free-transit (a transit stay without a visa), visa-on-arrival, e-visa (a new online visa), travel-authorisation (a pre-travel permit such as the UK ETA or the EU’s ETIAS becomes required), visa-required (visa-free entry ends).',
      values: ['visa-free', 'visa-free-transit', 'visa-on-arrival', 'e-visa', 'travel-authorisation', 'visa-required'],
      valueLabels: {
        'visa-free': 'Visa-free entry',
        'visa-free-transit': 'Visa-free transit',
        'visa-on-arrival': 'Visa on arrival',
        'e-visa': 'New e-visa',
        'travel-authorisation': 'Travel authorisation needed',
        'visa-required': 'Visa needed again',
      },
    },
    stay_days: {
      type: 'number',
      label: 'Longest stay',
      min: 0,
      max: 366,
      unit: 'days',
      help: 'The longest stay it allows, in days.',
    },
    effective_on: { type: 'date', label: 'From', required: true, help: 'The first day it applies.' },
    ends_on: { type: 'date', label: 'Until', help: 'The last day it applies, for a trial or temporary policy.' },
    issuer: {
      type: 'text',
      label: 'Announced by',
      required: true,
      max: 120,
      help: 'The government body that announced it, in English, e.g. Ministry of Foreign Affairs of China or UK Home Office.',
    },
    region: {
      type: 'enum',
      label: 'Region',
      required: true,
      help: 'The destination’s region.',
      values: ['americas', 'europe', 'asia-pacific', 'africa-middle-east'],
      valueLabels: {
        americas: 'Americas',
        europe: 'Europe',
        'asia-pacific': 'Asia-Pacific',
        'africa-middle-east': 'Africa & Middle East',
      },
    },
  },
  rules: [{ field: 'ends_on', notBefore: 'effective_on' }],
  accept: { effective_on: { from: 'today-180', to: 'today+365' } },
  example: {
    data: {
      title: 'Example Republic grants 30-day visa-free entry to visitors from three countries',
      destination: ['Example Republic'],
      travelers: ['Australia', 'New Zealand', 'Poland'],
      change: 'visa-free',
      stay_days: 30,
      effective_on: '2026-11-01',
      ends_on: '2027-12-31',
      issuer: 'Ministry of Foreign Affairs of the Example Republic',
      region: 'asia-pacific',
    },
    source_url: 'https://example.org/news/visa-free',
    evidence:
      'From November 1, 2026 to December 31, 2027, holders of ordinary passports from Australia, New Zealand and Poland may enter the Example Republic without a visa for stays of up to 30 days.',
  },
  table: {
    columns: ['title', 'destination', 'change', 'travelers', 'stay_days', 'effective_on', 'ends_on'],
    defaultSort: '-effective_on',
    previewTitle: 'Latest changes',
    previewColumns: ['title', 'destination', 'change', 'effective_on'],
  },
  charts: [
    { kind: 'count', title: 'Starting in the next 90 days', where: { effective_on: { from: 'today', to: 'today+90' } } },
    { kind: 'over-time', title: 'Changes by month they start', field: 'effective_on', bucket: 'month' },
    { kind: 'by-category', title: 'By kind of change', field: 'change' },
    { kind: 'by-category', title: 'Top destinations', field: 'destination' },
    { kind: 'by-category', title: 'Travellers who gain most', field: 'travelers' },
    { kind: 'histogram', title: 'Longest stay (days)', field: 'stay_days', edges: [0, 15, 30, 60, 90, 180] },
  ],
  scope: {
    in: 'Changes announced by a government to whether travellers of a nationality need a visa to visit or pass through a country or area: visa-free entry that starts, is extended or ends, visa-free transit, visa on arrival, new e-visas, and newly required travel authorisations such as the UK ETA or the EU’s ETIAS — starting in the last 180 days or the next 12 months.',
    out: 'Proposals and talks not yet adopted; work, study, residence and investor visas; fees, processing times and appointment rules alone; arrangements only for diplomatic or official passports; airline, travel-agency or visa-service pages as the only source.',
  },
  sourceHints: [
    'Foreign ministries and immigration authorities, such as China’s Ministry of Foreign Affairs, the UK Home Office on GOV.UK and the EU’s travel-europe.europa.eu',
    'Embassies’ and consulates’ notices',
    'Official tourism boards when they quote the rule',
    'Major news reports as leads: cite the government’s page when one exists',
  ],
  recheckAfterDays: 14,
  notify: { line: '{title} · {destination} · {change} · from {effective_on}' },
});
